"""Built-in default configuration."""
from __future__ import annotations

DEFAULTS = {
    "server": {
        "host": "0.0.0.0",
        "port": 8080,
        "request_timeout_seconds": 600,
        "max_body_bytes": 10485760,
    },
    "auth": {
        "enabled": True,
        "header": "Authorization",
        "allow_anonymous_health": True,
    },
    "provider": {
        "name": "openrouter",
        "base_url": "https://openrouter.ai/api/v1",
        "timeout_seconds": 120,
        "connect_timeout_seconds": 10,
        "max_retries": 2,
        "retry_backoff_seconds": 1.5,
        "retry_on_status": [429, 500, 502, 503, 504],
        "headers": {
            "HTTP-Referer": "http://localhost:8080",
            "X-Title": "Hermes Smart Router",
        },
        "context_window": 1000000,
    },
    "classification": {
        "enabled": True,
        "model": "mistralai/mistral-small-3.2-24b-instruct",
        "temperature": 0,
        "max_tokens": 60,
        "timeout_seconds": 8,
        "default_level": "L3",
        "min_confidence": 0.5,
        "low_confidence_action": "escalate",
        "rubric_version": "v1",
        "digest": {
            "system_chars": 500,
            "tail_chars": 2000,
            "include_tool_names": True,
            "include_context_summary": True,
            "strip_scaffolding": True,
            "learn_common_prefix": True,
            "prefix_samples": 20,
            "min_prefix_chars": 200,
            "strip_sections_enabled": True,
            "keep_sections": [],
            "delimit_untrusted": True,
            "injection_guard": True,
        },
        "cache": {
            "enabled": True,
            "ttl_seconds": 3600,
            "max_entries": 10000,
        },
    },
    "session": {
        "enabled": True,
        "backend": "memory",
        "id_header": "X-Session-Id",
        "use_user_field": False,
        "fingerprint_fallback": True,
        "fingerprint_salt": "",
        "fingerprint_strip_patterns": [],
        "on_unidentifiable": "classify",
        "idle_ttl_seconds": 7200,
        "max_ttl_seconds": 86400,
        "max_turns": None,
        "max_sessions": 50000,
        "max_provisional_turns": 3,
        "lock_wait_ms": 5000,
        "lock_reservation_seconds": 30,
        "on_config_change": "keep_level",
        "escalation": {
            "enabled": True,
            "threshold": 3,
            "decay_per_turn": 1,
            "cooldown_turns": 3,
            "max_escalations_per_session": 2,
            "never_downgrade": True,
            "respect_max_level": True,
            "explicit_signals_enabled": True,
            "free_signals_enabled": True,
            "signal_weights": {
                "repair_language": 3,
                "tool_error_loop": 3,
                "deep_keywords": 2,
                "context_growth": 2,
                "truncation": 2,
                "degenerate_response": 2,
                "turn_depth": 1,
                "code_volume_growth": 1,
            },
            "escalate_after_turns": 12,
            "escalate_on_context_growth_tokens": 24000,
            "huge_context_hard_override": True,
            "shadow_classify_every_n_turns": None,
            "reclassify_every_n_turns": None,
            "retry_on_failure": False,
            "retry_on_failure_max_per_session": 2,
        },
    },
    "heuristics": {
        "enabled": True,
        "measure": "task_payload",
        "huge_context_tokens": 32000,
    },
    "routing": {
        "allow_passthrough": False,
        "expose_upstream_models": True,
        "global_max_level": "L4",
        "global_min_level": "L1",
        "L1": {
            "label": "trivial",
            "model": "meta-llama/llama-3.3-8b-instruct",
            "fallbacks": [],
            "params": {},
            "max_cost_per_request_usd": 0.005,
        },
        "L2": {
            "label": "easy",
            "model": "openai/gpt-4.1-mini",
            "fallbacks": [],
            "params": {},
            "max_cost_per_request_usd": 0.02,
        },
        "L3": {
            "label": "medium",
            "model": "anthropic/claude-sonnet-4.5",
            "fallbacks": [],
            "params": {},
            "max_cost_per_request_usd": 0.20,
        },
        "L4": {
            "label": "hard",
            "model": "anthropic/claude-opus-4.5",
            "fallbacks": [],
            "params": {},
            "max_cost_per_request_usd": 1.00,
        },
    },
    "budget": {
        "enabled": False,
        "daily_limit_usd": 25.0,
        "on_exceeded": "downgrade",
        "downgrade_to": "L2",
    },
    "telemetry": {
        "log_level": "INFO",
        "log_format": "json",
        "log_prompts": False,
        "log_prompt_hash": True,
        "include_metadata_in_body": False,
        "metrics_enabled": True,
        "temporal_awareness": {
            "enabled": False,
            "default_timezone": "UTC",
            "strategy": "replace",
        },
    },
}
